# Generated by Django 4.1.7 on 2023-04-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopifyApp', '0002_coupon_created_at_coupon_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='rule_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
