# Generated by Django 4.1.7 on 2023-04-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopifyApp', '0003_coupon_rule_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='rule_id',
        ),
    ]
