# Generated by Django 4.1.7 on 2023-03-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Influencer',
        ),
    ]
