# Generated by Django 4.1.7 on 2023-03-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InfluencerApp', '0002_delete_influencer'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industries', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('promotion', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_age', models.IntegerField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
