# Generated by Django 4.1.7 on 2023-03-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerApp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerdetails',
            name='customer_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
