# Generated by Django 4.1.7 on 2023-03-28 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0002_alter_campaign_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='Influencerid',
        ),
    ]
