# Generated by Django 4.1.7 on 2023-03-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0003_remove_campaign_influencerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(null=True, upload_to='CampaignApp/static/images'),
        ),
    ]
