# Generated by Django 4.1.7 on 2023-03-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0004_campaign_date_campaign_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='product_name',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='image',
        ),
        migrations.AddField(
            model_name='campaign',
            name='influencer_visit',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='offer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='product_discount',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
