# Generated by Django 4.1.7 on 2023-03-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0005_rename_product_name_campaign_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
