# Generated by Django 4.1.7 on 2023-04-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0007_campaign_vendorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_status',
            field=models.IntegerField(default=0),
        ),
    ]
