# Generated by Django 4.1.7 on 2023-04-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0009_alter_campaign_influencer_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
