# Generated by Django 4.1.7 on 2023-04-09 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CampaignApp', '0011_productdetails_vendorid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencee', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=0)),
                ('campaignid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='CampaignApp.campaign')),
                ('vendorid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
