# Generated by Django 4.1.5 on 2023-03-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.IntegerField(null=True),
        ),
    ]
