# Generated by Django 4.1.7 on 2023-03-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='catagory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shopify_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
