# Generated by Django 4.1.7 on 2023-03-29 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_user_catagory_user_instagram_url_user_shopify_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='catagory',
            new_name='category',
        ),
    ]
