# Generated by Django 4.1.7 on 2023-04-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_rename_catagory_user_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shopify_url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
