# Generated by Django 4.1.7 on 2023-04-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_alter_user_shopify_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('2', 'Influencer'), ('3', 'Vendor')], default='', max_length=255),
        ),
    ]
